import React from 'react'
import { GetServerSideProps } from 'next'
import { AxiosResponse } from 'axios'
import { ICollectionResponse, IArticles } from '../../types'
import { fetchArticle } from '../../http'
import Head from 'next/head'
import qs from 'qs'
import Image from 'next/image';
import {formatDate,serializemarkdown} from '../../utils/index'
import { MDXRemote,MDXRemoteSerializeResult } from 'next-mdx-remote'
import { it } from 'node:test'
interface IProptype{
    item:IArticles
    notFound:boolean
   }

const slug = ({item, notFound=false}:IProptype) => {
  const url=process.env.API_URL;
  return (
    
<>
<Head>
       <title className='text-primary'>CodersBlog</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
     <div className= 'my-12 grid lg:grid-cols-3 gap-12 single-article'>

<div className=' col-span-2'>
<h1 className=' text-3xl font-bold py-4'>{item.attributes.Title}</h1>
<div className='flex items-center my-4'>
       <div className=' rounded-lg overflow-hidden flex items-center justify-center mr-2'>
           <Image src={`${url}${item.attributes.author.data.attributes.avtar.data.attributes.formats.thumbnail.url}`}
           height={40}
           width={40}
           />
       </div>
       <span className='text-sm font-bold text-gray-600'>
           {item.attributes.author.data.attributes.firstname}{" "}
           {item.attributes.author.data.attributes.lastname} on   </span>
       <span className='text-sm font-normal text-gray-400 ml-2'>
               {formatDate(item.attributes.createdAt)}
              
       </span>
   </div>

   <div className='text-lg text-gray-600 leading-8'>
      <img className='w-full max-h-80 my-12 mb-6'
       src={`http://localhost:1337${item.attributes.Image.data.attributes.url}`}

      
      alt={`${item.attributes.Title}`} />


    <MDXRemote {...(item.attributes.Body as MDXRemoteSerializeResult)} />
    
   </div>




</div>
{/* <div className='mt-12 m-4 p-2'>

<span className=' text-xl  font-semibold m-4'>Sign up to our newsletter</span>
<br />
<h6 className=' text-sm  text-gray-500 m-4'>Get the latest article on all things data delivered straight to your inbox</h6>
<input className='m-4  border-2  px-4 rounded-md ' type="e-mail" placeholder='Your work mail' />
<br />
<button className='m-4 text-primary border-2 border-primary rounded-md p-2 '>Subscribe</button>

</div> */}
      
    </div>
</>
  )
}

export const getServerSideProps:GetServerSideProps=async({query})=>{
 
    const option={
        populate:['Image','author.avtar'],
        filters:{
          slug:{
            $eq:query.slug
          }
        }
      }
      const queryString=qs.stringify(option);
      const{data:articles}:AxiosResponse<ICollectionResponse<IArticles[]>>=await fetchArticle(queryString);


   return{
props:{
  
 item:await serializemarkdown(articles.data[0])
 
}

 }
}






export default slug